# Generated by Django 5.0 on 2023-12-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menus'),
        ),
    ]
