# Generated by Django 5.0 on 2023-12-29 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_order_menu_order_dish_alter_menu_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetail',
            name='factura',
        ),
        migrations.CreateModel(
            name='BillHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='BillHeader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.billheader'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
