# Generated by Django 5.0 on 2023-12-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_billdetail_factura_billheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='BillHeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.billheader'),
        ),
        migrations.DeleteModel(
            name='BillDetail',
        ),
    ]
